-- POKEMON insertions

INSERT INTO POKEMON (ID,NAME,TYPE, NAMET, INSERTIME) VALUES (37,'Vulpix','Fire','',0);
INSERT INTO POKEMON (ID,NAME,TYPE, NAMET, INSERTIME) VALUES (6,'Charizard','Fire','',0);
INSERT INTO POKEMON (ID,NAME,TYPE, NAMET, INSERTIME) VALUES (126,'Magmar','Fire','',0);
INSERT INTO POKEMON (ID,NAME,TYPE, NAMET, INSERTIME) VALUES (154,'Cyndaquil','Fire','',0);
INSERT INTO POKEMON (ID,NAME,TYPE, NAMET, INSERTIME) VALUES (653,'Fennekin','Fire','',0);


INSERT INTO POKEMON (ID,NAME,TYPE, NAMET, INSERTIME) VALUES (134,'Vaporeon','Water','',0);
INSERT INTO POKEMON (ID,NAME,TYPE, NAMET, INSERTIME) VALUES (55,'Golduck','Water','',0);
INSERT INTO POKEMON (ID,NAME,TYPE, NAMET, INSERTIME) VALUES (99,'Kingler','Water','',0);
INSERT INTO POKEMON (ID,NAME,TYPE, NAMET, INSERTIME) VALUES (129,'Magikarp','Water','',0);
INSERT INTO POKEMON (ID,NAME,TYPE, NAMET, INSERTIME) VALUES (131,'Lapras','Water','',0);


INSERT INTO POKEMON (ID,NAME,TYPE, NAMET, INSERTIME) VALUES (1,'Bulbasaur','Grass','',0);
INSERT INTO POKEMON (ID,NAME,TYPE, NAMET, INSERTIME) VALUES (071,'Victreebel','Grass','',0);
INSERT INTO POKEMON (ID,NAME,TYPE, NAMET, INSERTIME) VALUES (152,'Chikorita','Grass','',0);
INSERT INTO POKEMON (ID,NAME,TYPE, NAMET, INSERTIME) VALUES (192,'Sunflora','Grass','',0);
INSERT INTO POKEMON (ID,NAME,TYPE, NAMET, INSERTIME) VALUES (319,'Sharpedo','Grass','',0);

-- TRAINERS insertions

INSERT INTO TRAINERS (NAME,LEVEL, BAGSIZE) VALUES ('Rach',8, 0);
INSERT INTO TRAINERS (NAME,LEVEL, BAGSIZE) VALUES ('Rache',0, 0);
INSERT INTO TRAINERS (NAME,LEVEL, BAGSIZE) VALUES ('Rachel',1, 0);
INSERT INTO TRAINERS (NAME,LEVEL, BAGSIZE) VALUES ('Racheli',2, 0);
INSERT INTO TRAINERS (NAME,LEVEL, BAGSIZE) VALUES ('RacheliA',5, 0);
INSERT INTO TRAINERS (NAME,LEVEL, BAGSIZE) VALUES ('Empty',7, 0);
INSERT INTO TRAINERS (NAME,LEVEL, BAGSIZE) VALUES ('A',8, 0);
INSERT INTO TRAINERS (NAME,LEVEL, BAGSIZE) VALUES ('B',4, 2);
INSERT INTO TRAINERS (NAME,LEVEL, BAGSIZE) VALUES ('C',2, 0);
INSERT INTO TRAINERS (NAME,LEVEL, BAGSIZE) VALUES ('D',5, 9);
